"""AIS vessel metadata helpers (MMSI flag lookup, ship type labels)."""

from __future__ import annotations

# ITU Maritime Identification Digits → (ISO 3166-1 alpha-2, country name).
# Subset covering common Baltic / global traffic; unknown MIDs fall back to None.
_MID_COUNTRY: dict[int, tuple[str, str]] = {
    201: ("AL", "Albania"),
    202: ("AD", "Andorra"),
    203: ("AT", "Austria"),
    204: ("PT", "Azores"),
    205: ("BE", "Belgium"),
    206: ("BY", "Belarus"),
    207: ("BG", "Bulgaria"),
    208: ("VA", "Vatican"),
    209: ("CY", "Cyprus"),
    210: ("CY", "Cyprus"),
    211: ("CY", "Cyprus"),
    212: ("CY", "Cyprus"),
    213: ("GE", "Georgia"),
    214: ("MD", "Moldova"),
    215: ("MT", "Malta"),
    216: ("AM", "Armenia"),
    218: ("DE", "Germany"),
    219: ("DK", "Denmark"),
    220: ("DK", "Denmark"),
    224: ("ES", "Spain"),
    225: ("ES", "Spain"),
    226: ("FR", "France"),
    227: ("FR", "France"),
    228: ("FR", "France"),
    229: ("MT", "Malta"),
    230: ("FI", "Finland"),
    231: ("FO", "Faroe Islands"),
    232: ("GB", "United Kingdom"),
    233: ("GB", "United Kingdom"),
    234: ("GB", "United Kingdom"),
    235: ("GB", "United Kingdom"),
    236: ("GI", "Gibraltar"),
    237: ("GR", "Greece"),
    238: ("HR", "Croatia"),
    239: ("GR", "Greece"),
    240: ("GR", "Greece"),
    241: ("GR", "Greece"),
    242: ("MA", "Morocco"),
    243: ("HU", "Hungary"),
    244: ("NL", "Netherlands"),
    245: ("NL", "Netherlands"),
    246: ("NL", "Netherlands"),
    247: ("IT", "Italy"),
    248: ("MT", "Malta"),
    249: ("MT", "Malta"),
    250: ("IE", "Ireland"),
    251: ("IS", "Iceland"),
    252: ("LI", "Liechtenstein"),
    253: ("LU", "Luxembourg"),
    254: ("MC", "Monaco"),
    255: ("PT", "Madeira"),
    256: ("MT", "Malta"),
    257: ("NO", "Norway"),
    258: ("NO", "Norway"),
    259: ("NO", "Norway"),
    261: ("RO", "Romania"),
    262: ("ME", "Montenegro"),
    263: ("SK", "Slovakia"),
    264: ("CZ", "Czech Republic"),
    265: ("SE", "Sweden"),
    266: ("SE", "Sweden"),
    267: ("SK", "Slovakia"),
    268: ("SM", "San Marino"),
    269: ("CH", "Switzerland"),
    270: ("UA", "Ukraine"),
    271: ("RS", "Serbia"),
    272: ("UA", "Ukraine"),
    273: ("RU", "Russia"),
    274: ("MK", "North Macedonia"),
    275: ("LV", "Latvia"),
    276: ("EE", "Estonia"),
    277: ("LT", "Lithuania"),
    278: ("SI", "Slovenia"),
    279: ("RS", "Serbia"),
    301: ("AI", "Anguilla"),
    303: ("US", "United States"),
    304: ("AG", "Antigua and Barbuda"),
    305: ("AG", "Antigua and Barbuda"),
    306: ("CW", "Curaçao"),
    307: ("AW", "Aruba"),
    308: ("BS", "Bahamas"),
    309: ("BS", "Bahamas"),
    310: ("BM", "Bermuda"),
    311: ("BS", "Bahamas"),
    312: ("BZ", "Belize"),
    314: ("BB", "Barbados"),
    316: ("CA", "Canada"),
    319: ("KY", "Cayman Islands"),
    321: ("CR", "Costa Rica"),
    323: ("CU", "Cuba"),
    325: ("DO", "Dominican Republic"),
    327: ("GT", "Guatemala"),
    329: ("HN", "Honduras"),
    330: ("HT", "Haiti"),
    331: ("US", "United States"),
    332: ("PR", "Puerto Rico"),
    334: ("MX", "Mexico"),
    336: ("PA", "Panama"),
    338: ("US", "United States"),
    339: ("JM", "Jamaica"),
    341: ("KN", "Saint Kitts and Nevis"),
    343: ("LC", "Saint Lucia"),
    345: ("VC", "Saint Vincent"),
    347: ("TT", "Trinidad and Tobago"),
    348: ("TC", "Turks and Caicos"),
    350: ("PA", "Panama"),
    351: ("PA", "Panama"),
    352: ("PA", "Panama"),
    353: ("PA", "Panama"),
    354: ("PA", "Panama"),
    355: ("PA", "Panama"),
    356: ("PA", "Panama"),
    357: ("PA", "Panama"),
    358: ("PA", "Panama"),
    359: ("SV", "El Salvador"),
    361: ("PM", "Saint Pierre and Miquelon"),
    362: ("TT", "Trinidad and Tobago"),
    364: ("TC", "Turks and Caicos"),
    366: ("US", "United States"),
    367: ("US", "United States"),
    368: ("US", "United States"),
    369: ("US", "United States"),
    370: ("PA", "Panama"),
    371: ("PA", "Panama"),
    372: ("PA", "Panama"),
    373: ("PA", "Panama"),
    374: ("PA", "Panama"),
    375: ("PA", "Panama"),
    376: ("PA", "Panama"),
    377: ("PA", "Panama"),
    378: ("PA", "Panama"),
    379: ("PA", "Panama"),
    401: ("AF", "Afghanistan"),
    403: ("SA", "Saudi Arabia"),
    405: ("BD", "Bangladesh"),
    408: ("BH", "Bahrain"),
    410: ("BT", "Bhutan"),
    412: ("CN", "China"),
    413: ("CN", "China"),
    414: ("CN", "China"),
    416: ("TW", "Taiwan"),
    417: ("LK", "Sri Lanka"),
    419: ("IN", "India"),
    422: ("IR", "Iran"),
    423: ("AZ", "Azerbaijan"),
    425: ("IQ", "Iraq"),
    428: ("IL", "Israel"),
    431: ("JP", "Japan"),
    432: ("JP", "Japan"),
    434: ("TM", "Turkmenistan"),
    436: ("KZ", "Kazakhstan"),
    437: ("UZ", "Uzbekistan"),
    438: ("JO", "Jordan"),
    440: ("KR", "South Korea"),
    441: ("KR", "South Korea"),
    443: ("PS", "Palestine"),
    445: ("KP", "North Korea"),
    447: ("KW", "Kuwait"),
    450: ("LB", "Lebanon"),
    451: ("KG", "Kyrgyzstan"),
    453: ("MO", "Macao"),
    455: ("MV", "Maldives"),
    457: ("MN", "Mongolia"),
    459: ("NP", "Nepal"),
    461: ("OM", "Oman"),
    463: ("PK", "Pakistan"),
    466: ("QA", "Qatar"),
    468: ("SY", "Syria"),
    470: ("AE", "United Arab Emirates"),
    472: ("TJ", "Tajikistan"),
    473: ("YE", "Yemen"),
    475: ("YE", "Yemen"),
    477: ("HK", "Hong Kong"),
    478: ("BA", "Bosnia and Herzegovina"),
    501: ("AQ", "Antarctica"),
    503: ("AU", "Australia"),
    506: ("MM", "Myanmar"),
    508: ("BN", "Brunei"),
    510: ("FM", "Micronesia"),
    511: ("PW", "Palau"),
    512: ("NZ", "New Zealand"),
    514: ("KH", "Cambodia"),
    515: ("KH", "Cambodia"),
    516: ("CX", "Christmas Island"),
    518: ("CK", "Cook Islands"),
    520: ("FJ", "Fiji"),
    523: ("CC", "Cocos Islands"),
    525: ("ID", "Indonesia"),
    529: ("KI", "Kiribati"),
    531: ("LA", "Laos"),
    533: ("MY", "Malaysia"),
    536: ("MP", "Northern Mariana Islands"),
    538: ("MH", "Marshall Islands"),
    540: ("NC", "New Caledonia"),
    542: ("NU", "Niue"),
    544: ("NR", "Nauru"),
    546: ("PF", "French Polynesia"),
    548: ("PH", "Philippines"),
    553: ("PG", "Papua New Guinea"),
    555: ("PN", "Pitcairn Islands"),
    557: ("SB", "Solomon Islands"),
    559: ("AS", "American Samoa"),
    561: ("WS", "Samoa"),
    563: ("SG", "Singapore"),
    564: ("SG", "Singapore"),
    565: ("SG", "Singapore"),
    566: ("SG", "Singapore"),
    567: ("TH", "Thailand"),
    570: ("TO", "Tonga"),
    572: ("TV", "Tuvalu"),
    574: ("VN", "Vietnam"),
    576: ("VU", "Vanuatu"),
    577: ("VU", "Vanuatu"),
    578: ("WF", "Wallis and Futuna"),
    601: ("ZA", "South Africa"),
    603: ("AO", "Angola"),
    605: ("DZ", "Algeria"),
    607: ("TF", "French Southern Territories"),
    608: ("IO", "British Indian Ocean Territory"),
    609: ("BI", "Burundi"),
    610: ("BJ", "Benin"),
    611: ("BW", "Botswana"),
    612: ("CF", "Central African Republic"),
    613: ("CM", "Cameroon"),
    615: ("CG", "Congo"),
    616: ("KM", "Comoros"),
    617: ("CV", "Cape Verde"),
    618: ("CI", "Côte d'Ivoire"),
    619: ("DJ", "Djibouti"),
    620: ("EG", "Egypt"),
    621: ("ET", "Ethiopia"),
    622: ("ER", "Eritrea"),
    623: ("GA", "Gabon"),
    624: ("GH", "Ghana"),
    625: ("GM", "Gambia"),
    626: ("GN", "Guinea"),
    627: ("GQ", "Equatorial Guinea"),
    628: ("GW", "Guinea-Bissau"),
    629: ("KE", "Kenya"),
    630: ("LR", "Liberia"),
    631: ("LS", "Lesotho"),
    632: ("LY", "Libya"),
    633: ("MG", "Madagascar"),
    634: ("ML", "Mali"),
    635: ("MZ", "Mozambique"),
    636: ("MR", "Mauritania"),
    637: ("MU", "Mauritius"),
    638: ("MW", "Malawi"),
    639: ("NA", "Namibia"),
    640: ("NE", "Niger"),
    641: ("NG", "Nigeria"),
    642: ("RE", "Réunion"),
    643: ("RW", "Rwanda"),
    644: ("SC", "Seychelles"),
    645: ("SD", "Sudan"),
    646: ("SN", "Senegal"),
    647: ("SC", "Seychelles"),
    648: ("SH", "Saint Helena"),
    649: ("SL", "Sierra Leone"),
    650: ("SO", "Somalia"),
    651: ("SZ", "Eswatini"),
    652: ("TD", "Chad"),
    653: ("TG", "Togo"),
    654: ("TN", "Tunisia"),
    655: ("TZ", "Tanzania"),
    656: ("UG", "Uganda"),
    657: ("CD", "DR Congo"),
    658: ("ZM", "Zambia"),
    659: ("ZW", "Zimbabwe"),
    701: ("AR", "Argentina"),
    710: ("BR", "Brazil"),
    720: ("BO", "Bolivia"),
    725: ("CL", "Chile"),
    730: ("CO", "Colombia"),
    735: ("EC", "Ecuador"),
    740: ("FK", "Falkland Islands"),
    745: ("GF", "French Guiana"),
    750: ("GY", "Guyana"),
    755: ("PY", "Paraguay"),
    760: ("PE", "Peru"),
    765: ("SR", "Suriname"),
    770: ("UY", "Uruguay"),
    775: ("VE", "Venezuela"),
}

# AIS ship type codes (ITU-R M.1371) → short display label.
_SHIP_TYPE_LABELS: dict[int, str] = {
    30: "Fishing",
    31: "Towing",
    32: "Towing (long)",
    33: "Dredger",
    34: "Diving",
    35: "Military",
    36: "Sailing",
    37: "Pleasure",
    40: "HSC",
    50: "Pilot",
    51: "SAR",
    52: "Tug",
    53: "Port tender",
    54: "Anti-pollution",
    55: "Law enforcement",
    58: "Medical",
    59: "Non-combatant",
    60: "Passenger",
    61: "Passenger",
    62: "Passenger",
    63: "Passenger",
    64: "Passenger",
    65: "Passenger",
    66: "Passenger",
    67: "Passenger",
    68: "Passenger",
    69: "Passenger",
    70: "Cargo",
    71: "Cargo",
    72: "Cargo",
    73: "Cargo",
    74: "Cargo",
    75: "Cargo",
    76: "Cargo",
    77: "Cargo",
    78: "Cargo",
    79: "Cargo",
    80: "Tanker",
    81: "Tanker",
    82: "Tanker",
    83: "Tanker",
    84: "Tanker",
    85: "Tanker",
    86: "Tanker",
    87: "Tanker",
    88: "Tanker",
    89: "Tanker",
    90: "Other",
    91: "Other",
    92: "Other",
    93: "Other",
    94: "Other",
    95: "Other",
    96: "Other",
    97: "Other",
    98: "Other",
    99: "Other",
}


def mid_from_mmsi(mmsi: int | str) -> int | None:
    text = str(mmsi).strip()
    if len(text) < 3 or not text.isdigit():
        return None
    return int(text[:3])


def flag_from_mmsi(mmsi: int | str) -> str | None:
    """ISO 3166-1 alpha-2 flag code derived from MMSI maritime ID."""
    mid = mid_from_mmsi(mmsi)
    if mid is None:
        return None
    entry = _MID_COUNTRY.get(mid)
    return entry[0] if entry else None


def country_from_mmsi(mmsi: int | str) -> str | None:
    """Country name derived from MMSI maritime ID."""
    mid = mid_from_mmsi(mmsi)
    if mid is None:
        return None
    entry = _MID_COUNTRY.get(mid)
    return entry[1] if entry else None


def ship_type_label(code: int | str | None) -> str | None:
    if code is None:
        return None
    try:
        numeric = int(code)
    except (TypeError, ValueError):
        text = str(code).strip()
        return text or None
    if numeric == 0:
        return None
    if label := _SHIP_TYPE_LABELS.get(numeric):
        return label
    if 20 <= numeric <= 29:
        return "WIG"
    return f"Type {numeric}"
